#DELETE FROM library.user WHERE account='controller';
INSERT INTO library.user(name,account,password,isAdministrator,email) values('controller','controller','controller',1,'grassking100@gmail.com');
#DROP USER 'controller'@'localhost';
CREATE USER 'controller'@'localhost' IDENTIFIED BY 'controller';
GRANT ALL privileges ON *.* To 'controller'@'localhost' WITH GRANT OPTION;
flush privileges;
#DELETE FROM library.user WHERE account='guest';
INSERT INTO library.user(name,account,password,isAdministrator,email) values('guest','guest','guest',0,'grassking100@gmail.com');
#DROP USER 'guest'@'localhost';
CREATE USER 'guest'@'localhost' IDENTIFIED BY 'guest';
GRANT SELECT ON library.book To 'guest'@'localhost';
flush privileges;
GRANT SELECT ON library.author To 'guest'@'localhost';
flush privileges;
GRANT SELECT ON library.publisher To 'guest'@'localhost';
flush privileges;
GRANT SELECT ON library.book_has_author To 'guest'@'localhost';
flush privileges;
GRANT SELECT ON library.physical_book To 'guest'@'localhost';
flush privileges;